# golangci-lint configuration for DuckDuckGo Chat CLI
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      # Allow ignoring errors for these specific functions
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment  # Can be too strict for readability
      
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: duckduckgo-chat-cli
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    ignore-words:
      - duckchat
      - duckduckgo
      
  unused:
    check-exported: false
    
  unparam:
    check-exported: false
    
  gosec:
    excludes:
      - G204  # Subprocess launched with variable (common in CLI tools)
      - G104  # Errors unhandled (we handle with errcheck)
      
  cyclop:
    max-complexity: 15
    
  funlen:
    lines: 80
    statements: 50
    
  gocognit:
    min-complexity: 20
    
  nestif:
    min-complexity: 5
    
  lll:
    line-length: 120
    
  revive:
    confidence: 0.8
    rules:
      - name: exported-function
      - name: exported-type
      - name: exported-var
      - name: package-comments
        disabled: true  # Disable for CLI tools
      - name: comment-spacings

linters:
  enable:
    - errcheck        # Check for unhandled errors
    - gosimple        # Simplify code
    - govet           # Standard go vet checks
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Advanced static analysis
    - typecheck       # Type checking
    - unused          # Check for unused code
    - gofmt           # Format checking
    - goimports       # Import format checking
    - misspell        # Spell checking
    - unconvert       # Remove unnecessary conversions
    - unparam         # Check for unused parameters
    - gosec           # Security checks
    - goconst         # Check for repeated strings
    - gocognit        # Cognitive complexity
    - nestif          # Nested if statements
    - prealloc        # Slice preallocation
    - predeclared     # Check for predeclared identifiers
    - revive          # Replacement for golint
    - whitespace      # Whitespace detection
    - gci             # Control golang package import order
    - cyclop          # Package cyclomatic complexity
    - funlen          # Function length
    - lll             # Line length
    
  disable:
    - deadcode        # Deprecated, replaced by unused
    - varcheck        # Deprecated, replaced by unused
    - structcheck     # Deprecated, replaced by unused
    - golint          # Deprecated, replaced by revive
    - interfacer      # Deprecated
    - scopelint       # Deprecated
    - maligned        # Deprecated
    - exhaustivestruct # Too strict
    - exhaustruct     # Too strict
    - gochecknoglobals # Too strict for CLI tools
    - gochecknoinits  # Too strict for CLI tools
    - godox           # TODOs are fine during development
    - wrapcheck       # Too strict for CLI tools
    - forbidigo       # Too restrictive
    - tagliatelle     # JSON tag format not always needed
    
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocognit
        - errcheck
        - dupl
        - gosec
        - funlen
        
    # Exclude security checks for test files
    - path: _test\.go
      text: "G404:"  # Use of weak random number generator
      
    # Allow long lines in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll
        
    # Allow complexity in main files
    - path: cmd/
      linters:
        - gocognit
        - cyclop
        - funlen
        
    # Allow globals in configuration
    - path: internal/config/
      linters:
        - gochecknoglobals
        
  exclude-use-default: false
  exclude:
    # Exclude some staticcheck messages
    - "SA9003:"  # Empty branch
    - "SA1019:"  # Using deprecated function
    
  fix: false

severity:
  default-severity: major
  case-sensitive: false
